#!/bin/bash -e
set +h
# Linux From Scratch
# File: lfs_profile
# LFS ENVAR Source File/Script
#####################################################################
#  Can be sourced by a script to obtain system-specific values.
#  Should first be run with system-name as argument to configure.
#  This is also a great reference for the various system specific values.
#
#  Currently configured system names:
#+ Kate
#+ Bobby
#+ Gorgak
#+ Tyrone
#+ Lilu
#+ Artemis
#+ Eos
#+ Nyx
#+ Selene
#+ Pebbles
##############################################################################
names="Bobby, Gorgak, Tyrone, Kate, Lilu, Artemis, Eos, Nyx, Selene, Pebbles"
scriptdir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -n $0 ] && [[ $0 == *lfs_profile ]] && [ -n $1 ]; then
([ $1 = 'Bobby' -o $1 = "Bobby" ] && sed -i '100,549s/^\([^#]\)/#\1/' ${DIR}/lfs_profile &&
    sed -i '100,149s/^#\([^#]\)/\1/' ${DIR}/lfs_profile && exit 0)||
([ $1 = 'Gorgak' ] && sed -i '100,549s/^\([^#]\)/#\1/' ${DIR}/lfs_profile &&
    sed -i '150,199s/^#\([^#]\)/\1/' ${DIR}/lfs_profile && exit 0) ||
([ $1 = 'Tyrone' ] && sed -i '100,549s/^\([^#]\)/#\1/' ${DIR}/lfs_profile &&
    sed -i '200,249s/^#\([^#]\)/\1/' ${DIR}/lfs_profile && exit 0) ||
([ $1 = 'Kate' ] && sed -i '100,549s/^\([^#]\)/#\1/' ${DIR}/lfs_profile &&
    sed -i '250,299s/^#\([^#]\)/\1/' ${DIR}/lfs_profile && exit 0) ||
([ $1 = 'Lilu' ] && sed -i '100,549s/^\([^#]\)/#\1/' ${DIR}/lfs_profile &&
    sed -i '300,349s/^#\([^#]\)/\1/' ${DIR}/lfs_profile && exit 0) ||
([ $1 = 'Artemis' ] && sed -i '100,549s/^\([^#]\)/#\1/' ${DIR}/lfs_profile &&
    sed -i '350,399s/^#\([^#]\)/\1/' ${DIR}/lfs_profile && exit 0) ||
([ $1 = 'Eos' ] && sed -i '100,549s/^\([^#]\)/#\1/' ${DIR}/lfs_profile &&
    sed -i '400,449s/^#\([^#]\)/\1/' ${DIR}/lfs_profile && exit 0)||
([ $1 = 'Nyx' ] && sed -i '100,549s/^\([^#]\)/#\1/' ${DIR}/lfs_profile &&
    sed -i '450,499s/^#\([^#]\)/\1/' ${DIR}/lfs_profile && exit 0) ||
([ $1 = 'Selene' ] && sed -i '100,54s/^\([^#]\)/#\1/' ${DIR}/lfs_profile &&
    sed -i '500,549s/^#\([^#]\)/\1/' ${DIR}/lfs_profile && exit 0) ||
([ $1 = 'Pebbles' ] && sed -i '100,54s/^\([^#]\)/#\1/' ${DIR}/lfs_profile &&
    sed -i '500,549s/^#\([^#]\)/\1/' ${DIR}/lfs_profile && exit 0) ||
([ $1 = '-n' -o $1 = '--names' ] && echo $NAMES && exit 0) ||
echo "Usage: $0 <system-name>" && exit 1
fi
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#####################################################################
# As source
##^^^^^^^^^
##Bobby - LFS (53,82):
#export ARCH="x86_64"
##4.000
#export PROFILE="LFS LFSDEV LFSREPO CHRISTENED SURNAME"
#export CHRISTENED="Bobby"
##7.040
#export CDROM="sr0 sr1"
#export PERSIST="by-path"
##7.050
#export IFACE=(enp0s10)
#export IVARS=(SERVICE IP GATEWAY PREFIX BROADCAST)
#export SERVICE_enp0s10="ipv4-static"
#export IP_enp0s10="192.168.0.17"
#export GATEWAY_enp0s10="192.168.0.1"
#export PREFIX_enp0s10="24"
#export BROADCAST_enp0s10="192.168.0.255"
#export HOSTNAME="Bobby"
##8.030 - CHRISTENED, SURNAME, BOOTDEV
##8.040 - CHRISTENED, SURNAME, BOOTDEV, LFSDEV
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
###################################################################
##Gorgak - LFS (83,112):
#export ARCH="x86_64"
##4.000
#export PROFILE="LFS LFSDEV CHRISTENED SURNAME"
#export CHRISTENED="Gorgak"
##7.040
#export CDROM="sr0"
#export PERSIST="by-path"
##7.050
#export IFACE=(enp2s0)
#export IVARS=(SERVICE IP GATEWAY PREFIX BROADCAST)
#export SERVICE_enp2s0="ipv4-static"
#export IP_enp2s0="192.168.15.69"
#export GATEWAY_enp2s0="192.168.15.1"
#export PREFIX_enp2s0="24"
#export BROADCAST_enp2s0="192.168.15.255"
#export HOSTNAME="Gorgak"
##8.030 - CHRISTENED, BOOTDEV
##8.040 - CHRISTENED, BOOTDEV, LFSDEV
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#####################################################################
##Tyrone - LFS (113,142):
#export ARCH="x86"
##4.000
#export PROFILE="LFS LFSDEV CHRISTENED SURNAME"
#export CHRISTENED="Tyrone"
##7.040
#export CDROM="sr0"
#export PERSIST="by-path"
##7.050
#export IFACE=(enp2s0)
#export IVARS=(SERVICE IP GATEWAY PREFIX BROADCAST)
#export SERVICE_enp2s0="ipv4-static"
#export IP_enp2s0="192.168.0.12"
#export GATEWAY_enp2s0="192.168.0.1"
#export PREFIX_enp2s0="24"
#export BROADCAST_enp2s0="192.168.0.255"
#export HOSTNAME="Tyrone"
##8.030 - CHRISTENED, BOOTDEV
##8.040 - CHRISTENED, BOOTDEV, LFSDEV
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#####################################################################
##Kate - LFS (143,176):
#export ARCH="x86_64"
##4.000
#export PROFILE="LFS LFSDEV LFSDEV1 LFSDEV2 LFSDEV3 LFSDEV4 CHRISTENED SURNAME"
#export CHRISTENED="Kate"
##7.040
#export CDROM="sr0 sr1"
#export PERSIST="by-path"
##7.050
#export IFACE=(enp0s10)
#export IVARS=(SERVICE IP GATEWAY PREFIX BROADCAST)
#export SERVICE_enp0s10="ipv4-static"
#export IP_enp0s10="192.168.0.17"
#export GATEWAY_enp0s10="192.168.0.1"
#export PREFIX_enp0s10="24"
#export BROADCAST_enp0s10="192.168.0.255"
#export HOSTNAME="Kate"
##8.030 - CHRISTENED, BOOTDEV
##8.040 - CHRISTENED, BOOTDEV, LFSDEV
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#####################################################################
##Lilu - LFS (177,203):
export ARCH="x86_64"
##4.000
export PROFILE="LFS LFSDEV CHRISTENED SURNAME"
export CHRISTENED="Lilu"
##7.040
export CDROM="sr0 sr1"
export PERSIST="by-path"
##7.050
export IFACE=(enp10s0)
export IVARS=(SERVICE IP GATEWAY PREFIX BROADCAST)
export SERVICE_enp10s0="ipv4-static"
export IP_enp10s0="192.168.0.33"
export GATEWAY_enp10s0="192.168.0.1"
export PREFIX_enp10s0="24"
export BROADCAST_enp10s0="192.168.0.255"
export HOSTNAME="Lilu"
##8.030 - CHRISTENED, BOOTDEV
##8.040 - CHRISTENED, BOOTDEV, LFSDEV
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#####################################################################
##Artemis - LFS (305,335):
#export ARCH="x86_64"
##4.000
#export PROFILE="LFS LFSDEV CHRISTENED SURNAME"
#export CHRISTENED="Artemis"
##7.040
#export CDROM="sr0"
#export PERSIST="by-path"
##7.050
#export IFACE=(enp10s2)
#export IVARS=(SERVICE IP GATEWAY PREFIX BROADCAST)
#export SERVICE_enp2s0="ipv4-static"
#export IP_enp3s0="192.168.0.14"
#export GATEWAY_enp3s0="192.168.0.1"
#export PREFIX_enp3s0="24"
#export BROADCAST_enp3s0="192.168.0.255"
#export HOSTNAME="Artemis"
##8.030 - CHRISTENED, BOOTDEV
##8.040 - CHRISTENED, BOOTDEV, LFSDEV
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#####################################################################
##Eos - LFS (204,233):
#export ARCH="ARM"
##4.000
#export PROFILE="LFS LFSDEV CHRISTENED SURNAME"
#export CHRISTENED="Eos"
##7.040
#export CDROM=
#export PERSIST=
##7.050
#export IFACE=(enp2s0)
#export IVARS=(SERVICE IP GATEWAY PREFIX BROADCAST)
#export SERVICE_enp2s0="ipv4-static"
#export IP_enp2s0="192.168.0.18"
#export GATEWAY_enp2s0="192.168.0.1"
#export PREFIX_enp2s0="24"
#export BROADCAST_enp2s0="192.168.0.255"
#export HOSTNAME="Eos"
##8.030 - CHRISTENED, BOOTDEV
##8.040 - CHRISTENED, BOOTDEV, LFSDEV
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#####################################################################
##Nyx - LFS (234,263):
#export ARCH="x86"
##4.000
#export PROFILE="LFS LFSDEV CHRISTENED SURNAME"
#export CHRISTENED="Nyx"
##7.040
#export CDROM=
#export PERSIST=
##7.050
#export IFACE=(enp3s0)
#export IVARS=(SERVICE IP GATEWAY PREFIX BROADCAST)
#export SERVICE_enp3s0="ipv4-static"
#export IP_enp3s0="192.168.0.14"
#export GATEWAY_enp3s0="192.168.0.1"
#export PREFIX_enp3s0="24"
#export BROADCAST_enp3s0="192.168.0.255"
#export HOSTNAME="Nyx"
##8.030 - CHRISTENED, BOOTDEV
##8.040 - CHRISTENED, BOOTDEV, LFSDEV
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#####################################################################
##Selene - LFS (264,293):
#export ARCH="x86_64"
##4.000
#export PROFILE="LFS LFSDEV CHRISTENED SURNAME"
#export CHRISTENED="Selene"
##7.040
#export CDROM="sr0"
#export PERSIST="by-id"
##7.050
#export IFACE=(enp0s25)
#export IVARS=(SERVICE IP GATEWAY PREFIX BROADCAST)
#export SERVICE_enp0s25="ipv4-static"
#export IP_enp0s25="192.168.0.21"
#export GATEWAY_enp0s25="192.168.0.1"
#export PREFIX_enp0s25="24"
#export BROADCAST_enp0s25="192.168.0.255"
#export HOSTNAME="Selene"
##8.030 - CHRISTENED, BOOTDEV
##8.040 - CHRISTENED, BOOTDEV, LFSDEV
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#####################################################################
#
# Installation Variables
#export KVER="4.1.3"
#export LFSVER="20150803"
#export PARALLEL=$(($(getconf _NPROCESSORS_ONLN)+1))
#export LFS=/mnt/lfs
#export LFSREPO=${HOME}/Copy/LFS/LFS
#export LFSDEV=/dev/sda6
#export BOOTDEV=/dev/sda1
#export SWAPDEV=/dev/sda2
#export HOMEDEV=/dev/sda4
#export VARDEV=/dev/sda4
#export TMPDEV=/dev/sda4
#export SURNAME="lfs-${LFSVER}"
#####################################################################
#

































#####################################################################
#
# Program Versions - as of Version 7.8, updated 01/24/2016
VERSION-acl=2.2.52
VERSION-attr=2.4.47
VERSION-autoconf=2.69
VERSION-automake=1.15
VERSION-bash=4.3.30
VERSION-bc=1.06.95
VERSION-binutils=2.25.1
VERSION-bison=3.0.4
VERSION-bzip2=1.0.6
VERSION-check=0.10.0
VERSION-coreutils=8.24
VERSION-dejagnu=1.5.3
VERSION-diffutils=3.3
VERSION-eudev=3.1.5
VERSION-e2fsprogs=1.42.13
VERSION-expat=2.1.0
VERSION-expect=5.45
VERSION-file=5.25
VERSION-findutils=4.6.0
VERSION-flex=2.6.0
VERSION-gawk=4.1.3
VERSION-gcc=5.3.0
VERSION-gdbm=1.11
VERSION-gettext=0.19.7
VERSION-glibc=2.22
VERSION-gmp=6.1.0
VERSION-gperf=3.0.4
VERSION-grep=2.22
VERSION-groff=1.22.3
VERSION-grub=2.02~beta2
VERSION-gzip=1.6
VERSION-iana_etc=2.30
VERSION-inetutils=1.9.4
VERSION-intltool=0.51.0
VERSION-iproute2=4.4.0
VERSION-kbd=2.0.3
VERSION-kmod=22
VERSION-less=481
VERSION-lfs_bootscripts=20150222
VERSION-libcap=2.24
VERSION-libpipeline=1.4.1
VERSION-libtool=2.4.6
VERSION-linux=4.4
VERSION-m4=1.4.17
VERSION-make=4.1
VERSION-man_db=2.7.5
VERSION-man_pages=4.04
VERSION-mpc=1.0.3
VERSION-mpfr=3.1.3
VERSION-ncurses=6.0
VERSION-patch=2.7.5
VERSION-perl=5.22.1
VERSION-pkg_config=0.29
VERSION-procps_ng=3.3.11
VERSION-psmisc=22.21
VERSION-readline=6.3
VERSION-sed=4.2.2
VERSION-shadow=4.2.1
VERSION-sysklogd=1.5.1
VERSION-sysvinit=2.88dsf
VERSION-tar=1.28
VERSION-tcl_core=8.6.4
VERSION-texinfo=6.0
VERSION-tzdata=2015g
VERSION-udev_lfs=20140408
VERSION-util_linux=2.27.1
VERSION-vim=7.4
VERSION-XML_Parser=2.44
VERSION-xz=5.2.2
VERSION-zlib=1.2.8

#####################################################################

