#!/bin/bash -e
set +h
# Linux From Scratch
# File: lfs_profile
# LFS ENVAR Source File/Script
#####################################################################
#  Can be sourced by a script to obtain system-specific values.
#  Should first be run with system-name as argument to configure.
#  This is also a great reference for the various system specific values.
#
#  Currently configured system names:
#+ Kate
#+ Bobby
#+ Gorgak
#+ Tyrone
#+ Lilu
#+ Artemis
#+ Eos
#+ Nyx
#+ Selene
#
#####################################################################
NAMES="Bobby, Gorgak, Tyrone, Kate, Lilu, Artemis, Eos, Nyx, Selene"
DIR=$(dirname $0)
# As script, configure for current system:
if [ -n $0 ] && [[ $0 == *lfs_profile ]] && [ -n $1 ]; then
([ $1 = 'Bobby' -o $1 = "Bobby" ] && sed -i '100,549s/^\([^#]\)/#\1/' ${DIR}/lfs_profile &&
    sed -i '100,149s/^#\([^#]\)/\1/' ${DIR}/lfs_profile && exit 0)||
([ $1 = 'Gorgak' ] && sed -i '100,549s/^\([^#]\)/#\1/' ${DIR}/lfs_profile &&
    sed -i '150,199s/^#\([^#]\)/\1/' ${DIR}/lfs_profile && exit 0) ||
([ $1 = 'Tyrone' ] && sed -i '100,549s/^\([^#]\)/#\1/' ${DIR}/lfs_profile &&
    sed -i '200,249s/^#\([^#]\)/\1/' ${DIR}/lfs_profile && exit 0) ||
([ $1 = 'Kate' ] && sed -i '100,549s/^\([^#]\)/#\1/' ${DIR}/lfs_profile &&
    sed -i '250,299s/^#\([^#]\)/\1/' ${DIR}/lfs_profile && exit 0) ||
([ $1 = 'Lilu' ] && sed -i '100,549s/^\([^#]\)/#\1/' ${DIR}/lfs_profile &&
    sed -i '300,349s/^#\([^#]\)/\1/' ${DIR}/lfs_profile && exit 0) ||
([ $1 = 'Artemis' ] && sed -i '100,549s/^\([^#]\)/#\1/' ${DIR}/lfs_profile &&
    sed -i '350,399s/^#\([^#]\)/\1/' ${DIR}/lfs_profile && exit 0) ||
([ $1 = 'Eos' ] && sed -i '100,549s/^\([^#]\)/#\1/' ${DIR}/lfs_profile &&
    sed -i '400,449s/^#\([^#]\)/\1/' ${DIR}/lfs_profile && exit 0)||
([ $1 = 'Nyx' ] && sed -i '100,549s/^\([^#]\)/#\1/' ${DIR}/lfs_profile &&
    sed -i '450,499s/^#\([^#]\)/\1/' ${DIR}/lfs_profile && exit 0) ||
([ $1 = 'Selene' ] && sed -i '100,54s/^\([^#]\)/#\1/' ${DIR}/lfs_profile &&
    sed -i '500,549s/^#\([^#]\)/\1/' ${DIR}/lfs_profile && exit 0) ||
([ $1 = '-n' -o $1 = '--names' ] && echo $NAMES && exit 0) ||
echo "Usage: $0 <system-name>" && exit 1
fi
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#####################################################################
# As source
##^^^^^^^^^
##Bobby - LFS (53,82):
#export KVER="4.1.3"
#export ARCH="x86_64"
#export LFSVER="20150803"
#export PARALLEL=$(($(getconf _NPROCESSORS_ONLN)+1))
##4.000
#export PROFILE="LFS LFSDEV LFSREPO CHRISTENED SURNAME"
#export LFS=/mnt/lfs
#export LFSDEV=/dev/sda6
#export LFSREPO=${HOME}/Copy/LFS/LFS
#export CHRISTENED="Bobby"
#export SURNAME="lfs-${LFSVER}-1"
##7.040
#export CDROM="sr0 sr1"
#export PERSIST="by-path"
##7.050
#export IFACE=(enp0s10)
#export IVARS=(SERVICE IP GATEWAY PREFIX BROADCAST)
#export SERVICE_enp0s10="ipv4-static"
#export IP_enp0s10="192.168.0.17"
#export GATEWAY_enp0s10="192.168.0.1"
#export PREFIX_enp0s10="24"
#export BROADCAST_enp0s10="192.168.0.255"
#export HOSTNAME="Bobby"
##8.020 - LFSDEV
#export BOOTDEV=/dev/sda1
#export SWAPDEV=/dev/sda2
#export HOMEDEV=/dev/sda4
##8.030 - CHRISTENED, SURNAME, BOOTDEV
##8.040 - CHRISTENED, SURNAME, BOOTDEV, LFSDEV
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
###################################################################
##Gorgak - LFS (83,112):
#export KVER="4.1.5"
#export ARCH="x86_64"
#export LFSVER="20150820"
#export PARALLEL=$(($(getconf _NPROCESSORS_ONLN)+1))
##4.000
#export PROFILE="LFS LFSDEV CHRISTENED SURNAME"
#export LFS=/mnt/lfs
#export LFSDEV=/dev/sda1
#export LFSREPO=/LFS-${LFSVER}
#export CHRISTENED="Gorgak"
#export SURNAME="lfs-${LFSVER}"
##7.040
#export CDROM="sr0"
#export PERSIST="by-path"
##7.050
#export IFACE=(enp2s0)
#export IVARS=(SERVICE IP GATEWAY PREFIX BROADCAST)
#export SERVICE_enp2s0="ipv4-static"
#export IP_enp2s0="192.168.15.69"
#export GATEWAY_enp2s0="192.168.15.1"
#export PREFIX_enp2s0="24"
#export BROADCAST_enp2s0="192.168.15.255"
#export HOSTNAME="Gorgak"
##8.020 - LFSDEV
##export BOOTDEV=/dev/sda2
##export SWAPDEV=/dev/sda3
##export HOMEDEV=
##8.030 - CHRISTENED, BOOTDEV
##8.040 - CHRISTENED, BOOTDEV, LFSDEV
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#####################################################################
##Tyrone - LFS (113,142):
#export KVER="4.1.3"
#export ARCH="x86"
#export LFSVER="20150803"
#export PARALLEL=$(($(getconf _NPROCESSORS_ONLN)+1))
##4.000
#export PROFILE="LFS LFSDEV CHRISTENED SURNAME"
#export LFS=/mnt/lfs
#export LFSDEV=/dev/sda3
#export LFSREPO=${HOME}/Copy/LFS/LFS
#export CHRISTENED="Tyrone"
#export SURNAME="lfs-${LFSVER}"
##7.040
#export CDROM="sr0"
#export PERSIST="by-path"
##7.050
#export IFACE=(enp2s0)
#export IVARS=(SERVICE IP GATEWAY PREFIX BROADCAST)
#export SERVICE_enp2s0="ipv4-static"
#export IP_enp2s0="192.168.0.12"
#export GATEWAY_enp2s0="192.168.0.1"
#export PREFIX_enp2s0="24"
#export BROADCAST_enp2s0="192.168.0.255"
#export HOSTNAME="Tyrone"
##8.020 - LFSDEV
##export BOOTDEV=/dev/sda1
##export SWAPDEV=/dev/sda2
##export HOMEDEV=/dev/sda4
##8.030 - CHRISTENED, BOOTDEV
##8.040 - CHRISTENED, BOOTDEV, LFSDEV
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#####################################################################
##Kate - LFS (143,176):
#export KVER="4.1.3"
#export ARCH="x86_64"
#export LFSVER="20150803"
#export PARALLEL=$(($(getconf _NPROCESSORS_ONLN)+1))
##4.000
#export PROFILE="LFS LFSDEV LFSDEV1 LFSDEV2 LFSDEV3 LFSDEV4 CHRISTENED SURNAME"
#export LFS=/mnt/lfs
#export LFSDEV=/dev/sda9
#export LFSDEV1=/dev/sda6
#export LFSDEV2=/dev/sda7
#export LFSDEV3=/dev/sda8
#export LFSDEV4=/dev/sda9
#export LFSREPO=${HOME}/Copy/LFS/LFS
#export CHRISTENED="Kate"
#export SURNAME="lfs-${LFSVER}-4"
##7.040
#export CDROM="sr0 sr1"
#export PERSIST="by-path"
##7.050
#export IFACE=(enp0s10)
#export IVARS=(SERVICE IP GATEWAY PREFIX BROADCAST)
#export SERVICE_enp0s10="ipv4-static"
#export IP_enp0s10="192.168.0.17"
#export GATEWAY_enp0s10="192.168.0.1"
#export PREFIX_enp0s10="24"
#export BROADCAST_enp0s10="192.168.0.255"
#export HOSTNAME="Kate"
##8.020 - LFSDEV
##export BOOTDEV=/dev/sda1
##export SWAPDEV=/dev/sda2
##export HOMEDEV=/dev/sda4
##8.030 - CHRISTENED, BOOTDEV
##8.040 - CHRISTENED, BOOTDEV, LFSDEV
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#####################################################################
##Lilu - LFS (177,203):
export KVER="4.1.2"
export ARCH="x86_64"
export LFSVER="20150723"
export PARALLEL=$(($(getconf _NPROCESSORS_ONLN)+1))
##4.000
export PROFILE="LFS LFSDEV CHRISTENED SURNAME"
export LFS=/mnt/lfs
export LFSDEV=/dev/sda5
export LFSREPO=${HOME}/Copy/LFS/LFS
export CHRISTENED="Lilu"
export SURNAME="lfs"
##7.040
export CDROM="sr0 sr1"
export PERSIST="by-path"
##7.050
export IFACE=(enp10s0)
export IVARS=(SERVICE IP GATEWAY PREFIX BROADCAST)
export SERVICE_enp10s0="ipv4-static"
export IP_enp10s0="192.168.0.33"
export GATEWAY_enp10s0="192.168.0.1"
export PREFIX_enp10s0="24"
export BROADCAST_enp10s0="192.168.0.255"
export HOSTNAME="Lilu"
##8.020 - LFSDEV
export BOOTDEV=/dev/sda2
export SWAPDEV=/dev/sda3
##export HOMEDEV=
##8.030 - CHRISTENED, BOOTDEV
##8.040 - CHRISTENED, BOOTDEV, LFSDEV
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#####################################################################
##Artemis - LFS (305,335):
#export KVER="4.1.6"
#export ARCH="x86_64"
#export LFSVER="20150825"
#export PARALLEL=$(($(getconf _NPROCESSORS_ONLN)+1))
##4.000
#export PROFILE="LFS LFSDEV CHRISTENED SURNAME"
#export LFS=/mnt/lfs
#export LFSDEV=/dev/sda5
#export LFSREPO=/LFS-${LFSVER}
#export CHRISTENED="Artemis"
#export SURNAME="lfs-${LFSVER}"
##7.040
#export CDROM="sr0"
#export PERSIST="by-path"
##7.050
#export IFACE=(enp10s2)
#export IVARS=(SERVICE IP GATEWAY PREFIX BROADCAST)
#export SERVICE_enp2s0="ipv4-static"
#export IP_enp3s0="192.168.0.14"
#export GATEWAY_enp3s0="192.168.0.1"
#export PREFIX_enp3s0="24"
#export BROADCAST_enp3s0="192.168.0.255"
#export HOSTNAME="Artemis"
##8.020 - LFSDEV
##export BOOTDEV=
#export SWAPDEV=/dev/sda6
##export HOMEDEV=
##8.030 - CHRISTENED, BOOTDEV
##8.040 - CHRISTENED, BOOTDEV, LFSDEV
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#####################################################################
##Eos - LFS (204,233):
#export KVER="4.1.6"
#export ARCH="ARM"
#export LFSVER="20150825"
#export PARALLEL=$(($(getconf _NPROCESSORS_ONLN)+1))
##4.000
#export PROFILE="LFS LFSDEV CHRISTENED SURNAME"
#export LFS=/mnt/lfs
#export LFSDEV=/dev/sda1
#export LFSREPO=/LFS-${LFSVER}
#export CHRISTENED="Eos"
#export SURNAME="lfs-${LFSVER}"
##7.040
#export CDROM=
#export PERSIST=
##7.050
#export IFACE=(enp2s0)
#export IVARS=(SERVICE IP GATEWAY PREFIX BROADCAST)
#export SERVICE_enp2s0="ipv4-static"
#export IP_enp2s0="192.168.0.18"
#export GATEWAY_enp2s0="192.168.0.1"
#export PREFIX_enp2s0="24"
#export BROADCAST_enp2s0="192.168.0.255"
#export HOSTNAME="Eos"
##8.020 - LFSDEV
##export BOOTDEV=
##export SWAPDEV=
##export HOMEDEV=
##8.030 - CHRISTENED, BOOTDEV
##8.040 - CHRISTENED, BOOTDEV, LFSDEV
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#####################################################################
##Nyx - LFS (234,263):
#export KVER="4.1.6"
#export ARCH="x86"
#export LFSVER="20150825"
#export PARALLEL=$(($(getconf _NPROCESSORS_ONLN)+1))
##4.000
#export PROFILE="LFS LFSDEV CHRISTENED SURNAME"
#export LFS=/mnt/lfs
#export LFSDEV=/dev/sda5
#export LFSREPO=/LFS-${LFSVER}
#export CHRISTENED="Nyx"
#export SURNAME="lfs-${LFSVER}"
##7.040
#export CDROM=
#export PERSIST=
##7.050
#export IFACE=(enp3s0)
#export IVARS=(SERVICE IP GATEWAY PREFIX BROADCAST)
#export SERVICE_enp3s0="ipv4-static"
#export IP_enp3s0="192.168.0.14"
#export GATEWAY_enp3s0="192.168.0.1"
#export PREFIX_enp3s0="24"
#export BROADCAST_enp3s0="192.168.0.255"
#export HOSTNAME="Nyx"
##8.020 - LFSDEV
##export BOOTDEV=
#export SWAPDEV=/dev/sda6
##export HOMEDEV=
##8.030 - CHRISTENED, BOOTDEV
##8.040 - CHRISTENED, BOOTDEV, LFSDEV
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#####################################################################
##Selene - LFS (264,293):
#export KVER="4.2"
#export ARCH="x86_64"
#export LFSVER="20150915"
#export PARALLEL=$(($(getconf _NPROCESSORS_ONLN)+1))
##4.000
#export PROFILE="LFS LFSDEV CHRISTENED SURNAME"
#export LFS=/mnt/lfs
#export LFSDEV=/dev/sda2
#export LFSREPO=/LFS-${LFSVER}
#export CHRISTENED="Selene"
#export SURNAME="lfs-${LFSVER}"
##7.040
#export CDROM="sr0"
#export PERSIST="by-id"
##7.050
#export IFACE=(enp0s25)
#export IVARS=(SERVICE IP GATEWAY PREFIX BROADCAST)
#export SERVICE_enp0s25="ipv4-static"
#export IP_enp0s25="192.168.0.21"
#export GATEWAY_enp0s25="192.168.0.1"
#export PREFIX_enp0s25="24"
#export BROADCAST_enp0s25="192.168.0.255"
#export HOSTNAME="Selene"
##8.020 - LFSDEV
##export BOOTDEV=
#export SWAPDEV=/dev/sda1
##export HOMEDEV=
##8.030 - CHRISTENED, BOOTDEV
##8.040 - CHRISTENED, BOOTDEV, LFSDEV
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#####################################################################

